# Install Prometheus from Ansible Galaxy
- src: cloudalchemy.prometheus
  version: 2.16.3

# Install Grafana from Ansible Galaxy
- src: cloudalchemy.grafana
  version: 0.18.0

# Install AlertManager from Ansible Galaxy
- src: cloudalchemy.alertmanager
  version: 0.19.1

# Install Apache from Ansible Galaxy
- src: geerlingguy.apache
  version: 3.1.4

## Install Apache from Ansible Galaxy
- src: geerlingguy.certbot
  version: 3.1.0
