---
- name: pre-tasks| create temporary directory
  tempfile:
    state: directory
  register: tmpdir
  delegate_to: localhost

- name: pre-tasks| generate Grafana dashboards from templates
  include_tasks: 
    file: generate-dashboards.yml
    apply:
      delegate_to: localhost
  loop: "{{ clients }}"
  loop_control:
    loop_var: client

- name: pre-tasks| generating Prometheus playbook
  template:
    src: prometheus/playbook.yml.j2
    dest: "{{ tmpdir.path }}/prometheus-playbook.yml"
  delegate_to: localhost
