---
- name: pre-tasks| create temporary directory
  tempfile:
    state: directory
  register: tmpdir
  delegate_to: localhost
  tags:
  - generate-rules

- name: pre-tasks| create temporary Grafana directory
  file:
    path: "{{ tmpdir.path }}/grafana"
    state: directory
  delegate_to: localhost

- name: pre-tasks| create temporary Prometheus directory
  file:
    path: "{{ tmpdir.path }}/prometheus"
    state: directory
  delegate_to: localhost
  tags:
  - generate-rules

- name: pre-tasks| generate Grafana dashboards from templates
  include_tasks: 
    file: generate-dashboards.yml
    apply:
      delegate_to: localhost
  loop: "{{ clients }}"
  loop_control:
    loop_var: client

- name: pre-tasks| generate Prometheus rules from templates
  include_tasks:
    file: generate-rules.yml
    apply:
      delegate_to: localhost
  loop: "{{ clients }}"
  loop_control:
    loop_var: client
  tags:
  - generate-rules

- name: pre-tasks| generating Prometheus playbook
  template:
    src: prometheus/playbook.yml.j2
    dest: "{{ tmpdir.path }}/prometheus/prometheus-playbook.yml"
  delegate_to: localhost
