---
- name: pre-check| create temporary directory
  tempfile:
    state: directory
  register: tmpdir
  delegate_to: localhost

- name: Generate Grafana dashboards from templates
  include_tasks: 
    file: generate-dashboards.yml
    apply:
      delegate_to: localhost
  loop: "{{ clients }}"
  loop_control:
    loop_var: client
